//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace RudeValidation.Web.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MeetingStoreEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MeetingStoreEntities object using the connection string found in the 'MeetingStoreEntities' section of the application configuration file.
        /// </summary>
        public MeetingStoreEntities() : base("name=MeetingStoreEntities", "MeetingStoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MeetingStoreEntities object.
        /// </summary>
        public MeetingStoreEntities(string connectionString) : base(connectionString, "MeetingStoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MeetingStoreEntities object.
        /// </summary>
        public MeetingStoreEntities(EntityConnection connection) : base(connection, "MeetingStoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Location> Locations
        {
            get
            {
                if ((_Locations == null))
                {
                    _Locations = base.CreateObjectSet<Location>("Locations");
                }
                return _Locations;
            }
        }
        private ObjectSet<Location> _Locations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Meeting> Meetings
        {
            get
            {
                if ((_Meetings == null))
                {
                    _Meetings = base.CreateObjectSet<Meeting>("Meetings");
                }
                return _Meetings;
            }
        }
        private ObjectSet<Meeting> _Meetings;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Locations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLocations(Location location)
        {
            base.AddObject("Locations", location);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Meetings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMeetings(Meeting meeting)
        {
            base.AddObject("Meetings", meeting);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MeetingStoreModel", Name="Location")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Location : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Location object.
        /// </summary>
        /// <param name="locationId">Initial value of the LocationId property.</param>
        /// <param name="locationName">Initial value of the LocationName property.</param>
        public static Location CreateLocation(global::System.Int32 locationId, global::System.String locationName)
        {
            Location location = new Location();
            location.LocationId = locationId;
            location.LocationName = locationName;
            return location;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LocationId
        {
            get
            {
                return _LocationId;
            }
            set
            {
                if (_LocationId != value)
                {
                    OnLocationIdChanging(value);
                    ReportPropertyChanging("LocationId");
                    _LocationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LocationId");
                    OnLocationIdChanged();
                }
            }
        }
        private global::System.Int32 _LocationId;
        partial void OnLocationIdChanging(global::System.Int32 value);
        partial void OnLocationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LocationName
        {
            get
            {
                return _LocationName;
            }
            set
            {
                OnLocationNameChanging(value);
                ReportPropertyChanging("LocationName");
                _LocationName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LocationName");
                OnLocationNameChanged();
            }
        }
        private global::System.String _LocationName;
        partial void OnLocationNameChanging(global::System.String value);
        partial void OnLocationNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MeetingStoreModel", Name="Meeting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Meeting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Meeting object.
        /// </summary>
        /// <param name="meetingId">Initial value of the MeetingId property.</param>
        /// <param name="start">Initial value of the Start property.</param>
        /// <param name="end">Initial value of the End property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="location">Initial value of the Location property.</param>
        /// <param name="minimumAttendees">Initial value of the MinimumAttendees property.</param>
        /// <param name="maximumAttendees">Initial value of the MaximumAttendees property.</param>
        public static Meeting CreateMeeting(global::System.Int32 meetingId, global::System.DateTime start, global::System.DateTime end, global::System.String title, global::System.String location, global::System.Int16 minimumAttendees, global::System.Int16 maximumAttendees)
        {
            Meeting meeting = new Meeting();
            meeting.MeetingId = meetingId;
            meeting.Start = start;
            meeting.End = end;
            meeting.Title = title;
            meeting.Location = location;
            meeting.MinimumAttendees = minimumAttendees;
            meeting.MaximumAttendees = maximumAttendees;
            return meeting;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MeetingId
        {
            get
            {
                return _MeetingId;
            }
            set
            {
                if (_MeetingId != value)
                {
                    OnMeetingIdChanging(value);
                    ReportPropertyChanging("MeetingId");
                    _MeetingId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MeetingId");
                    OnMeetingIdChanged();
                }
            }
        }
        private global::System.Int32 _MeetingId;
        partial void OnMeetingIdChanging(global::System.Int32 value);
        partial void OnMeetingIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Start
        {
            get
            {
                return _Start;
            }
            set
            {
                OnStartChanging(value);
                ReportPropertyChanging("Start");
                _Start = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Start");
                OnStartChanged();
            }
        }
        private global::System.DateTime _Start;
        partial void OnStartChanging(global::System.DateTime value);
        partial void OnStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime End
        {
            get
            {
                return _End;
            }
            set
            {
                OnEndChanging(value);
                ReportPropertyChanging("End");
                _End = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("End");
                OnEndChanged();
            }
        }
        private global::System.DateTime _End;
        partial void OnEndChanging(global::System.DateTime value);
        partial void OnEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Details
        {
            get
            {
                return _Details;
            }
            set
            {
                OnDetailsChanging(value);
                ReportPropertyChanging("Details");
                _Details = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Details");
                OnDetailsChanged();
            }
        }
        private global::System.String _Details;
        partial void OnDetailsChanging(global::System.String value);
        partial void OnDetailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 MinimumAttendees
        {
            get
            {
                return _MinimumAttendees;
            }
            set
            {
                OnMinimumAttendeesChanging(value);
                ReportPropertyChanging("MinimumAttendees");
                _MinimumAttendees = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MinimumAttendees");
                OnMinimumAttendeesChanged();
            }
        }
        private global::System.Int16 _MinimumAttendees;
        partial void OnMinimumAttendeesChanging(global::System.Int16 value);
        partial void OnMinimumAttendeesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 MaximumAttendees
        {
            get
            {
                return _MaximumAttendees;
            }
            set
            {
                OnMaximumAttendeesChanging(value);
                ReportPropertyChanging("MaximumAttendees");
                _MaximumAttendees = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaximumAttendees");
                OnMaximumAttendeesChanged();
            }
        }
        private global::System.Int16 _MaximumAttendees;
        partial void OnMaximumAttendeesChanging(global::System.Int16 value);
        partial void OnMaximumAttendeesChanged();

        #endregion
    
    }

    #endregion
    
}
